// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-mo4ifERmbZFbRt-di0gRdRQ200RlvZg',
    appId: '1:114506886437:web:61186275fbd212d9f9fecc',
    messagingSenderId: '114506886437',
    projectId: 'emsprivate-e92ec',
    authDomain: 'emsprivate-e92ec.firebaseapp.com',
    storageBucket: 'emsprivate-e92ec.firebasestorage.app',
    measurementId: 'G-HHNNN20DFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMSGfUhNK_3uBna_e_GKw1Q7TniknToAA',
    appId: '1:114506886437:android:1311af3580c08947f9fecc',
    messagingSenderId: '114506886437',
    projectId: 'emsprivate-e92ec',
    storageBucket: 'emsprivate-e92ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGhw8zoxfarC2Pq_p7oxfuDGTsS59yOlE',
    appId: '1:114506886437:ios:745ae96520ee1d3df9fecc',
    messagingSenderId: '114506886437',
    projectId: 'emsprivate-e92ec',
    storageBucket: 'emsprivate-e92ec.firebasestorage.app',
    iosClientId: '114506886437-i5kfial6h4elb686uuj8lqp2vjsead6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAloneTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGhw8zoxfarC2Pq_p7oxfuDGTsS59yOlE',
    appId: '1:114506886437:ios:745ae96520ee1d3df9fecc',
    messagingSenderId: '114506886437',
    projectId: 'emsprivate-e92ec',
    storageBucket: 'emsprivate-e92ec.firebasestorage.app',
    iosClientId: '114506886437-i5kfial6h4elb686uuj8lqp2vjsead6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAloneTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-mo4ifERmbZFbRt-di0gRdRQ200RlvZg',
    appId: '1:114506886437:web:0b3511d22507c0bef9fecc',
    messagingSenderId: '114506886437',
    projectId: 'emsprivate-e92ec',
    authDomain: 'emsprivate-e92ec.firebaseapp.com',
    storageBucket: 'emsprivate-e92ec.firebasestorage.app',
    measurementId: 'G-6736FR5P83',
  );
}
